name: mindmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  flutter_sound: ^9.2.13+1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.1
  in_app_purchase: ^3.1.11
  # msal_flutter: ^2.0.1  # Removed due to build issues
dependency_overrides:
  device_calendar: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true